resources:
  - name: dwpdigital-packer
    type: registry-image-resource
    source:
      repository: dwpdigital/packer
    check_every: 5m

  - name: ecr-dwpdigital-packer-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "packer"

  - name: ecr-dwpdigital-packer
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "packer"
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci

jobs:
  - name: mirror-dwpdigital-packer-dev
    serial_groups: [packer]
    plan:
      - get: dwpdigital-packer
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-packer-dev
        params:
          image: "dwpdigital-packer/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-packer
    serial_groups: [packer]
    plan:
      - get: dwpdigital-packer
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-packer
        params:
          image: "dwpdigital-packer/image.tar"
        attempts: 3
