jobs:
  - name: packer-pr
    plan:
      - get: packer-pr
        trigger: true
        version: every
      - put: packer-pr
        params:
          path: packer-pr
          status: pending
        input_mapping:
          packer: packer-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          packer: packer-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          packer: packer-pr
        params:
          TF_WORKSPACE: "management-dev"
          DETAILED_EXITCODE: ""
        on_failure:
          put: packer-pr
          params:
            path: packer-pr
            status: failure
        on_success:
          put: packer-pr
          params:
            path: packer-pr
            status: success
